[package]
name = "testplugin_test"
version = "0.1.0"
authors = ["Steffen <steffen.butzer@outlook.com>"]

[lib]
name="testplugin_test"
path = "src/plugin.rs"
plugin = true

[dependencies]
aster = "0.9.2"
